import {TaskProvider} from '../context/task/TaskProvider'
import Navbar from '@/components/Navbar'
import {Toaster} from './Toaster'

import './globals.css'


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <Navbar/>
        <TaskProvider>
        {children}
        <Toaster/>
        </TaskProvider>
      </body>
    </html>
  )
}
